# Generated by Django 2.1 on 2018-08-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=2)),
                ('mobileNumber', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.FileField(upload_to='')),
                ('education', models.CharField(max_length=200)),
                ('hometown', models.CharField(max_length=200)),
                ('currentCity', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=500)),
                ('job', models.CharField(max_length=200)),
                ('interest', models.CharField(max_length=300)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permit.PermitUser')),
            ],
        ),
    ]
