# Generated by Django 2.1 on 2018-09-01 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='currentCity',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='profilePic',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PermitUser',
        ),
    ]
