# Generated by Django 2.1 on 2018-09-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0002_auto_20180901_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='firstname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
