# Generated by Django 2.1 on 2018-09-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0003_userinfo_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='firstname',
            new_name='currentCity',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='firstName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hometown',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='mobileNumber',
            field=models.CharField(default='', max_length=200),
        ),
    ]
