# Generated by Django 2.1 on 2018-09-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0004_auto_20180901_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='firstName',
        ),
    ]
