# Generated by Django 2.1 on 2018-09-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0007_userinfo_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
